### ISSUE TITLE
End of support for python 2.7

### ISSUE THREAD

**Issue by slfpercy** [certsocietegenerale/fame#75] opened 2019-12-18 21:33 UTC
### Description
Hello, I want to ask you if you have any update plan for Fame since python 2.7 isn't going to have support in 2020.

**Comment by lucebac** [comment] 2019-12-19 22:53
We already ported the whole FAME codebase (including the modules) to Python3 internally. We are happy to share all of that with the community but before I need to fix up my hilariously large feature PR to discuss with the team whether or not to include the changes into FAME.
Once we are done with that it should be no effort to provide the Python3 port of the code.

**Comment by dadokkio** [comment] 2020-03-26 10:42
hello, any update on this topic?

**Comment by lucebac** [comment] 2020-04-18 11:21
to make it short: no. I am still waiting for someone to review and merge the currently open pull requests so that I can provide the python 3 port more easily without having to manually find an remove any non-related fixes or feature additions.

**Comment by garanews** [comment] 2020-04-21 08:23
Do you need someone test it?

**Comment by lucebac** [comment] 2020-04-27 15:20
Not now, but as soon as the PR is open you are invited to test the python3 port.

**Comment by garanews** [comment] 2020-05-07 13:57
Ok let me know so we can start working on integration with Cortex Analyzer

**Comment by LowcaPromocji** [comment] 2020-06-18 05:34
What's the current status of python 3 port?

**Comment by MatteoManzoni** [comment] 2020-11-08 21:31
Me and 2 people from my team are really interested in the porting of the project to python3, if @lucebac can share his codebase even if half-backed we can pick-up his job. We hope to avoid starting from scratch

**Comment by lucebac** [comment] 2020-11-09 11:16
The port to python3 is complete and working fine, I will check with our team and upload the code once permitted.

**Comment by MatteoManzoni** [comment] 2020-11-09 11:19
Thank you! Let me know if we can help in any way

**Comment by lucebac** [comment] 2020-11-11 13:42
Minor Heads-Up for the watchers: I'm currently in the process of gathering all source code for publishing the Python 3 port. This should be done in the course of the day. I will let you know when I'm ready and where the code can be found then.

**Comment by lucebac** [comment] 2020-11-11 17:15
Ok, that went faster than I thought. Here you are: https://github.com/GDATAAdvancedAnalytics/fame/tree/python3

**Note**: the python 3 port is based off a set of changes that is not yet merged into the main FAME repository (read: it's based off "our" master branch). Nevertheless, the database(s) and config files are still compatible with the official code base, so switching from one to another *should* not break anything. Yet, as usual, please backup your data before switching.

**Note 2**: we implemented the Docker container(s) differently than what is in the official repo. Those two installements **are not easily interchangeable**. Please know what you are doing if you want to switch from one to the other.

**Comment by MatteoManzoni** [comment] 2020-11-11 17:20
Great thanks!

**Comment by gaelmuller** [comment] 2020-11-12 08:35
I have also been working on a Python 3 port that I just pushed to the `python3` branch. We cannot switch the `master` branch to the Python 3 version just yet because work remains on modules. I have created an issue in the `fame_modules` repository to track migration status:

https://github.com/certsocietegenerale/fame_modules/issues/40

When using the python3 port, please make sure you are using the `python3` branch both for the core and the modules. Contributions are welcome by testing the ports and / or migrating modules if necessary.

**Comment by dadokkio** [comment] 2020-11-12 09:10
I was trying to run docker version but I'm not able to access the gui.
The installation steps I've used:
```
git clone https://github.com/GDATAAdvancedAnalytics/fame.git
git checkout python3
cd fame
ssh-keygen -o [...]
make
docker network create traefik_default
docker-compose up
```

At first run web was missing zip so I've installed it manually
```
docker-compose exec fame-web bash
apt update
apt install p7zip-full
```
All the services are up but I'm not able to access the gui neither using localhost or ip. I've tried both 80, 8080 or 4200 port.

```
(base) dadokkio@Q:~/Desktop/DOCKER/fame$ docker-compose logs fame-web 
Attaching to fame-web
fame-web       | [+] Ensuring empty __init__.py in modules directory
fame-web       | [+] Adjusting permissions
fame-web       | [+] Waiting 60 seconds for MongoDB to come up
fame-web       | [+] Using existing virtualenv.
fame-web       | 
fame-web       | [+] Creating initial data ...
fame-web       | [+] Creating users...
fame-web       | [+] There are already users in the database.
fame-web       | [+] User for worker already created.
fame-web       | [+] Community repository already installed.
fame-web       | [+] Running webserver
fame-web       | *** Starting uWSGI 2.0.19.1 (64bit) on [Thu Nov 12 09:06:53 2020] ***
fame-web       | compiled with version: 8.3.0 on 12 November 2020 08:08:29
fame-web       | os: Linux-5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020
fame-web       | nodename: fame-web
fame-web       | machine: x86_64
fame-web       | clock source: unix
fame-web       | detected number of CPU cores: 16
fame-web       | current working directory: /fame
fame-web       | detected binary path: /fame/env/bin/uwsgi
fame-web       | !!! no internal routing support, rebuild with pcre support !!!
fame-web       | setuid() to 1000
fame-web       | *** WARNING: you are running uWSGI without its master process manager ***
fame-web       | your memory page size is 4096 bytes
fame-web       | detected max file descriptor number: 1048576
fame-web       | lock engine: pthread robust mutexes
fame-web       | thunder lock: disabled (you can enable it with --thunder-lock)
fame-web       | uWSGI http bound on :8080 fd 4
fame-web       | spawned uWSGI http 1 (pid: 22)
fame-web       | uwsgi socket 0 bound to TCP address 127.0.0.1:34465 (port auto-assigned) fd 3
fame-web       | Python version: 3.7.9 (default, Oct 13 2020, 21:10:49)  [GCC 8.3.0]
fame-web       | PEP 405 virtualenv detected: /fame/env
fame-web       | Set PythonHome to /fame/env
fame-web       | *** Python threads support is disabled. You can enable it with --enable-threads ***
fame-web       | Python main interpreter initialized at 0x561737431c40
fame-web       | your server socket listen backlog is limited to 100 connections
fame-web       | your mercy for graceful operations on workers is 60 seconds
fame-web       | mapped 72904 bytes (71 KB) for 1 cores
fame-web       | *** Operational MODE: single process ***
fame-web       | WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x561737431c40 pid: 1 (default app)
fame-web       | *** uWSGI is running in multiple interpreter mode ***
fame-web       | spawned uWSGI worker 1 (and the only) (pid: 1, cores: 1)
fame-web       | [pid: 1|app: 0|req: 1/1] 172.26.0.4 () {34 vars in 497 bytes} [Thu Nov 12 09:06:53 2020] GET /modules/download => generated 120 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 129 bytes (1 switches on core 0)
```

I'm missing something or I've done something wrong?

**Comment by lucebac** [comment] 2020-11-12 10:32
> I have also been working on a Python 3 port that I just pushed to the `python3` branch. We cannot switch the `master` branch to the Python 3 version just yet because work remains on modules. I have created an issue in the `fame_modules` repository to track migration status:
> 
> [certsocietegenerale/fame_modules#40](https://github.com/certsocietegenerale/fame_modules/issues/40)
> 
> When using the python3 port, please make sure you are using the `python3` branch both for the core and the modules. Contributions are welcome by testing the ports and / or migrating modules if necessary.

We have also ported the modules which I unfortunately forgot to upload by accident. I will upload them today and create a merge request.

**Comment by lucebac** [comment] 2020-11-12 10:36
> I was trying to run docker version but I'm not able to access the gui.
> The installation steps I've used:
> 
> ```
> git clone https://github.com/GDATAAdvancedAnalytics/fame.git
> git checkout python3
> cd fame
> ssh-keygen -o [...]
> make
> docker network create traefik_default
> docker-compose up
> ```
> 
> At first run web was missing zip so I've installed it manually
> 
> ```
> docker-compose exec fame-web bash
> apt update
> apt install p7zip-full
> ```

This is an interesting finding, I will look into that because the web container should not need to anything with 7zip as far as I can remember. Will check and report back.
 
> All the services are up but I'm not able to access the gui neither using localhost or ip. I've tried both 80, 8080 or 4200 port.
> 
> ```
> (base) dadokkio@Q:~/Desktop/DOCKER/fame$ docker-compose logs fame-web 
> Attaching to fame-web
> fame-web       | [+] Ensuring empty __init__.py in modules directory
> fame-web       | [+] Adjusting permissions
> fame-web       | [+] Waiting 60 seconds for MongoDB to come up
> fame-web       | [+] Using existing virtualenv.
> fame-web       | 
> fame-web       | [+] Creating initial data ...
> fame-web       | [+] Creating users...
> fame-web       | [+] There are already users in the database.
> fame-web       | [+] User for worker already created.
> fame-web       | [+] Community repository already installed.
> fame-web       | [+] Running webserver
> fame-web       | *** Starting uWSGI 2.0.19.1 (64bit) on [Thu Nov 12 09:06:53 2020] ***
> fame-web       | compiled with version: 8.3.0 on 12 November 2020 08:08:29
> fame-web       | os: Linux-5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020
> fame-web       | nodename: fame-web
> fame-web       | machine: x86_64
> fame-web       | clock source: unix
> fame-web       | detected number of CPU cores: 16
> fame-web       | current working directory: /fame
> fame-web       | detected binary path: /fame/env/bin/uwsgi
> fame-web       | !!! no internal routing support, rebuild with pcre support !!!
> fame-web       | setuid() to 1000
> fame-web       | *** WARNING: you are running uWSGI without its master process manager ***
> fame-web       | your memory page size is 4096 bytes
> fame-web       | detected max file descriptor number: 1048576
> fame-web       | lock engine: pthread robust mutexes
> fame-web       | thunder lock: disabled (you can enable it with --thunder-lock)
> fame-web       | uWSGI http bound on :8080 fd 4
> fame-web       | spawned uWSGI http 1 (pid: 22)
> fame-web       | uwsgi socket 0 bound to TCP address 127.0.0.1:34465 (port auto-assigned) fd 3
> fame-web       | Python version: 3.7.9 (default, Oct 13 2020, 21:10:49)  [GCC 8.3.0]
> fame-web       | PEP 405 virtualenv detected: /fame/env
> fame-web       | Set PythonHome to /fame/env
> fame-web       | *** Python threads support is disabled. You can enable it with --enable-threads ***
> fame-web       | Python main interpreter initialized at 0x561737431c40
> fame-web       | your server socket listen backlog is limited to 100 connections
> fame-web       | your mercy for graceful operations on workers is 60 seconds
> fame-web       | mapped 72904 bytes (71 KB) for 1 cores
> fame-web       | *** Operational MODE: single process ***
> fame-web       | WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x561737431c40 pid: 1 (default app)
> fame-web       | *** uWSGI is running in multiple interpreter mode ***
> fame-web       | spawned uWSGI worker 1 (and the only) (pid: 1, cores: 1)
> fame-web       | [pid: 1|app: 0|req: 1/1] 172.26.0.4 () {34 vars in 497 bytes} [Thu Nov 12 09:06:53 2020] GET /modules/download => generated 120 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 129 bytes (1 switches on core 0)
> ```
> 
> I'm missing something or I've done something wrong?

You need to add a reverse proxy to access the web interface [as stated in the docu](https://github.com/GDATAAdvancedAnalytics/fame/blob/python3/docs/installation.rst). If you only run it locally for debugging, you can add a port expose to be able to access the FAME web interface (port is 8080).

**Comment by dadokkio** [comment] 2020-11-12 10:58
Ok, adding a traefik service to docker-compose resolved the issue. Thanks :+1:

**Comment by lucebac** [comment] 2020-11-12 15:10
@dadokkio I can confirm your bug with p7zip missing in fame-web. To not clutter this issue, I will track this in https://github.com/GDATAAdvancedAnalytics/fame/issues/2

**Comment by gaelmuller** [comment] 2021-11-08 20:47
FAME has now been using Python 3 for a while

**Closed by gaelmuller** 2021-11-08 20:47 UTC
